DATA:
  dataset: vox
  data_root: ./VoxCeleb
  read_audio: True

  
LOSS:
  loss: MSE
  motion_weight: 1.0
  reg_weight: 1.0

NETWORK:
  arch: audio2vertices
  in_dim: 15069
  hidden_size: 1024
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  window_size: 1
  quant_factor: 0
  face_quan_num: 8
  neg: 0.2
  autoencoder: vertices_encoder
  INaffine: False
  style_emb_method: nnemb # onehot or nnemb

VQuantizer:
  n_embed: 728
  zquant_dim: 128

PREDICTOR:
  feature_dim: 1024
  vertice_dim: 15069
  device: cuda
  period: 30
  vqvae_pretrained_path: RUN/vox/CodeTalker_s1/model/model.pth.tar
  wav2vec2model_path: facebook/wav2vec2-base-960h
  teacher_forcing: True
  num_layers: 6
  n_head: 4 # not used

TRAIN:
  use_wandb: False
  use_sgd: False
  train_gpu: 0
  workers: 10  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  StepLR: False
  warmup_steps: 1
  adaptive_lr: False
  factor: 0.3
  patience: 3
  threshold: 0.0001
  epochs: 200
  step_size: 100
  gamma: 0.5
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.002
  manual_seed: 131
  print_freq: 100
  save_freq: 10
  save_path:
#  weight:
  weight:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
  visualize: True
  visualize_freq: 10
  # resume: 'RUN/vox/Head_s2/model/model.pth.tar'
  resume: False
  start_epoch: 0
  fps: 25

TEST:
  test_workers: 0
  test_gpu: 0
  test_batch_size: 1
  save: True
  model_path:
  save_folder: